// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrA-G7QOL6u8dtG5fNNDgIHroMaSBbvo',
    appId: '1:72926684055:web:5434b8fa76269728a2dad2',
    messagingSenderId: '72926684055',
    projectId: 'time-assistant-83393',
    authDomain: 'time-assistant-83393.firebaseapp.com',
    storageBucket: 'time-assistant-83393.appspot.com',
    measurementId: 'G-MQVTHPB0VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjssb18sqsIzYNtS-m7OtXHorFoiKEKUE',
    appId: '1:72926684055:android:1445ced153e03e64a2dad2',
    messagingSenderId: '72926684055',
    projectId: 'time-assistant-83393',
    storageBucket: 'time-assistant-83393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZxJ3EUZpgaJKykmm2pqEO5q6s5XGKfTI',
    appId: '1:72926684055:ios:d0885b0faedb0ebda2dad2',
    messagingSenderId: '72926684055',
    projectId: 'time-assistant-83393',
    storageBucket: 'time-assistant-83393.appspot.com',
    iosBundleId: 'com.hombreoso.timeassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZxJ3EUZpgaJKykmm2pqEO5q6s5XGKfTI',
    appId: '1:72926684055:ios:d0885b0faedb0ebda2dad2',
    messagingSenderId: '72926684055',
    projectId: 'time-assistant-83393',
    storageBucket: 'time-assistant-83393.appspot.com',
    iosBundleId: 'com.hombreoso.timeassistant',
  );
}
