// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCDPOE9YnI8OuLDIttopoo-AXtQ3oTgY',
    appId: '1:1026254620863:web:6863d47d5e321f8d5f1e0a',
    messagingSenderId: '1026254620863',
    projectId: 'time-mgmt-app-flutter',
    authDomain: 'time-mgmt-app-flutter.firebaseapp.com',
    storageBucket: 'time-mgmt-app-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf3jwx8RkJ2qEbGMFQik-LfA7UxXGf7J4',
    appId: '1:1026254620863:android:532a5ca47c73dbfe5f1e0a',
    messagingSenderId: '1026254620863',
    projectId: 'time-mgmt-app-flutter',
    storageBucket: 'time-mgmt-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBWEhQSx4idJUVo1G055gYhaWIJiUN6A',
    appId: '1:1026254620863:ios:ea7b809301d162015f1e0a',
    messagingSenderId: '1026254620863',
    projectId: 'time-mgmt-app-flutter',
    storageBucket: 'time-mgmt-app-flutter.appspot.com',
    iosClientId: '1026254620863-91k07at9r1qpr1cd1vjjitffdq7mq8s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeMgmtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBWEhQSx4idJUVo1G055gYhaWIJiUN6A',
    appId: '1:1026254620863:ios:ea7b809301d162015f1e0a',
    messagingSenderId: '1026254620863',
    projectId: 'time-mgmt-app-flutter',
    storageBucket: 'time-mgmt-app-flutter.appspot.com',
    iosClientId: '1026254620863-91k07at9r1qpr1cd1vjjitffdq7mq8s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeMgmtApp',
  );
}
